---
- hosts: 127.0.0.1
  become: yes
  become_method: sudo
  
  tasks:
    - name: Install standard packages
      apt:
        pkg: ['git', 'rsync', 'tmux', 'vim', 'zsh', 'fish']
        state: latest

    - name: Checkout dotfiles repository from GitHub
      git:
        repo: "https://github.com/jasonin2d/dotfiles.git"
        dest: "{{ lookup ('env', 'HOME') }}/dotfiles"

    - name: Change default shell to fish
      user:
        name: "{{ lookup ('env', 'USER') }}"
        shell: /usr/bin/fish

    - name: Link dotfiles
      file:
        src: "{{ lookup ('env', 'HOME') }}/dotfiles/{{ item }}"
        dest: "{{ lookup ('env', 'HOME') }}/.{{ item }}"
        state: link
      with_items:
        - tmux.conf
        - vimrc
        - zshrc

...
