---
- hosts: all
  become: yes
  become_method: sudo
  
  tasks:
    - name: Install standard packages
      apt:
        pkg: "{{ item }}"
        state: latest
      with_items:
        - git
        - rsync
        - tmux
        - vim
        - zsh

    - name: Checkout dotfiles repository from GitHub
      git:
        repo: "https://github.com/jasonin2d/dotfiles.git"
        dest: "{{ lookup ('env', 'HOME') }}/dotfiles"

    - name: Change default shell to zsh
      user:
        name: "{{ lookup ('env', 'USER') }}"
        shell: /usr/bin/zsh

    - name: Link dotfiles
      file:
        src: "{{ lookup ('env', 'HOME') }}/dotfiles/{{ item }}"
        dest: "{{ lookup ('env', 'HOME') }}/.{{ item }}"
        state: link
      with_items:
        - tmux.conf
        - vimrc
        - zshrc

...
